# Generated by Django 4.0.5 on 2022-07-08 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
