# Generated by Django 4.0.6 on 2022-07-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_is_featured_product_is_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_pingbacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
