# Generated by Django 4.0.6 on 2022-07-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_product_status_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productcode',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
