# Generated by Django 4.0.5 on 2022-07-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='contactsme',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(blank=True, default='images/not_found_image.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='aboutus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtpport',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='settings',
            name='status',
            field=models.CharField(choices=[('true', 'Açık'), ('false', 'Kapalı')], max_length=10),
        ),
    ]
