# Generated by Django 4.0.5 on 2022-07-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_settings_aboutus_alter_settings_contactsme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
