# Generated by Django 4.0.5 on 2022-07-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_settings_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='keywods',
            new_name='keywords',
        ),
    ]
