# Generated by Django 4.0.5 on 2022-07-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_keywods_settings_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='copyrighttext',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='settings',
            name='desightext',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='settings',
            name='desiglink',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
