# Generated by Django 4.0.5 on 2022-07-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_settings_copyrighttext_settings_desightext_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='desightext',
            new_name='designlink',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='desiglink',
            new_name='designtext',
        ),
    ]
