# Generated by Django 4.0.5 on 2022-07-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_settings_fimaptext_settings_finfotext'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='dribbble',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='settings',
            name='googleplus',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='settings',
            name='linkdn',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
