# Generated by Django 4.0.5 on 2022-07-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_contactformmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('New', 'Açık'), ('Read', 'Inceleniyor'), ('Closed', 'Kapandı')], default='New', max_length=10),
        ),
    ]
