# Generated by Django 4.0.5 on 2022-07-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_contactformmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
