# Generated by Django 4.0.6 on 2022-07-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_category_blogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BlogCategory',
        ),
    ]
