# Generated by Django 4.0.6 on 2022-07-11 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_category_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='author',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='blogs',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
