# Generated by Django 4.0.6 on 2022-07-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_blogs_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='number_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogs',
            name='number_of_pingbacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogs',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
