# Generated by Django 4.0.6 on 2022-07-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_blogs_number_of_comments_blogs_number_of_pingbacks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
