# Generated by Django 4.0.6 on 2022-07-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_blogcategory_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='status',
        ),
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
