# Generated by Django 4.0.6 on 2022-07-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_slider_price_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
